Update 92-mounts

diff --git a/qbittorrent/rootfs/etc/cont-init.d/92-mounts b/qbittorrent/rootfs/etc/cont-init.d/92-mounts
--- a/qbittorrent/rootfs/etc/cont-init.d/92-mounts
+++ b/qbittorrent/rootfs/etc/cont-init.d/92-mounts
@@ -1,31 +1,25 @@
 #!/usr/bin/with-contenv bashio
 
-####################
-# MOUNT SMB SHARES #
-####################
-# Mount CIFS Share if configured and if Protection Mode is active
+#########################
+# MOUNT SMB SHARES v1.0 #
+#########################
 if bashio::config.has_value 'networkdisks'; then
-    bashio::log.info 'Mounting smb share...'
+    # Mount CIFS Share if configured and if Protection Mode is active
+    bashio::log.info 'Mounting smb share(s)...'
+
+    # Define variables 
     MOREDISKS=$(bashio::config 'networkdisks')
     CIFS_USERNAME=$(bashio::config 'cifsusername')
     CIFS_PASSWORD=$(bashio::config 'cifspassword')
-    bashio::log.info "Network Disks mounting.. ${MOREDISKS}" && \
-    for disk in $MOREDISKS 
+
+    # Mounting disks
+    for disk in ${MOREDISKS//,/ }  # Separate comma separated values
     do
-        bashio::log.info "Mount ${disk}"
-        echo "Creating /mnt/storagecifs"
-        mkdir -p /mnt/storagecifs
-        chown -R abc:abc /mnt/storagecifs
-        mount -t cifs -o username=$CIFS_USERNAME,password=$CIFS_PASSWORD $disk /mnt/storagecifs && \
-        bashio::log.info "SMB share was successfully mapped to /mnt/storagecifs"   
-    done || \
-    bashio::log.warning "Protection mode is ON. Unable to mount external drives!"
+      disk=$(echo $disk | sed "s,/$,,") # Remove / at end of name
+      diskname=${disk##*/} # Get only last part of the name
+      mkdir -p /mnt/$diskname  # Create dir
+      chown -R root:root /mnt/$diskname  # Permissions
+      mount -t cifs -o username=$CIFS_USERNAME,password=$CIFS_PASSWORD $disk /mnt/$diskname && \
+      bashio::log.info "... $disk successfully mounted to /mnt/$diskname" || bashio::log.error "Unable to mount $disk to /mnt/$diskname with username $CIFS_USERNAME, $CIFS_PASSWORD" # Mount share
+    done || true
 fi
-
-#variable=abc,def,ghij
-#for i in ${variable//,/ }
-#do
-#    # call your procedure/other scripts here below
-#    echo "$i"
-#done
-
