Correct modules code

diff --git a/code-server/Dockerfile b/code-server/Dockerfile
--- a/code-server/Dockerfile
+++ b/code-server/Dockerfile
@@ -44,10 +44,9 @@ ARG MODULES="00-banner.sh 92-local_mounts.sh 92-smb_mounts.sh"
 # Automatic modules download
 RUN if ! command -v bash >/dev/null 2>/dev/null; then (apt-get update && apt-get install -yqq --no-install-recommends bash || apk add --no-cache bash); fi && \
     if ! command -v curl >/dev/null 2>/dev/null; then (apt-get update && apt-get install -yqq --no-install-recommends curl || apk add --no-cache curl); fi && \
-    mkdir -p /tmpscripts /etc/cont-init.d && \
-    for scripts in $MODULES; do curl -L -f -s "https://raw.githubusercontent.com/alexbelgium/hassio-addons/master/.templates/$scripts" -o /tmpscripts/"$scripts"; done  && \
-    if [ -d /etc/cont-init.d ]; then /bin/cp -rf /tmpscripts/* /etc/cont-init.d/ && chmod -R 755 /etc/cont-init.d; fi && \
-    rm -rf /tmpscripts || printf '%s\n' "${MODULES:-}" > /MODULESFILE
+    mkdir -p /etc/cont-init.d && \
+    for scripts in $MODULES; do curl -L -f -s -S "https://raw.githubusercontent.com/alexbelgium/hassio-addons/master/.templates/$scripts" -o /etc/cont-init.d/"$scripts" || echo "script failed to install $scripts"; done && \
+    chmod -R 755 /etc/cont-init.d || printf '%s\n' "${MODULES}" >/MODULESFILE
 
 # Manual apps
 ENV PACKAGES="jq"
