Update 41-folders

diff --git a/piwigo/rootfs/etc/cont-init.d/41-folders b/piwigo/rootfs/etc/cont-init.d/41-folders
--- a/piwigo/rootfs/etc/cont-init.d/41-folders
+++ b/piwigo/rootfs/etc/cont-init.d/41-folders
@@ -35,3 +35,9 @@ else
   ln -s /share/piwigo/keys /config
   echo "Using existing keys folder"
 fi
+
+##################
+# CORRECT CONFIG #
+##################
+sed -i "s|$conf['show_php_errors'] = E_ALL;|$conf['show_php_errors'] = E_ALL & ~E_NOTICE & ~E_DEPRECATED;|g" /gallery/local/config/config.inc.php && echo "config corrected for php error" || true
+
