Check installation

diff --git a/nextcloud/root/etc/cont-init.d/99-elasticsearch b/nextcloud/root/etc/cont-init.d/99-elasticsearch
--- a/nextcloud/root/etc/cont-init.d/99-elasticsearch
+++ b/nextcloud/root/etc/cont-init.d/99-elasticsearch
@@ -1,12 +1,12 @@
 #!/usr/bin/with-contenv bashio
 
 LAUNCHER="sudo -u abc php /data/config/www/nextcloud/occ" || bashio::log.info "/data/config/www/nextcloud/occ not found"
-    if ! bashio::fs.file_exists '/data/config/www/nextcloud/occ'; then
-        LAUNCHER=$(find / -name "occ" -print -quit)
-    fi || bashio::log.info "occ not found"
+if ! bashio::fs.file_exists '/data/config/www/nextcloud/occ'; then
+    LAUNCHER=$(find / -name "occ" -print -quit)
+fi || bashio::log.info "occ not found"
 
 # Make sure there is an Nextcloud installation
-if ! [ "$($LAUNCHER -V)" ]; then
+if [[ $($LAUNCHER -V) == *"not installed"* ]]; then
     bashio::log.warning "It seems there is no Nextcloud server installed. Please restart the addon after initialization of the user."
     exit 0
 fi
@@ -20,7 +20,7 @@ fi
 #################################################################################
 
 if bashio::config.true 'Full_Text_Search'; then
-    if [ $LAUNCHER fulltextsearch:index &>/dev/null ] ; then
+    if [ $LAUNCHER fulltextsearch:index ] &>/dev/null; then
         echo "Full Text Search is already working"
         break 2
     fi
@@ -42,35 +42,35 @@ if bashio::config.true 'Full_Text_Search'; then
     done
     chown -R abc:abc $NEXTCLOUD_PATH/apps
 
-if bashio::config.has_value 'elasticsearch_server'; then
-    HOST=$(bashio::config 'elasticsearch_server')
-else
-    bashio::log.warning 'Please define elasticsearch server url in addon options with the format "ip:port" such as "192.168.178.1:9200"'
-    HOST=$(bashio::network.ipv4_address)
-    HOST="${HOST%/*}:9200"
-fi 
+    if bashio::config.has_value 'elasticsearch_server'; then
+        HOST=$(bashio::config 'elasticsearch_server')
+    else
+        bashio::log.warning 'Please define elasticsearch server url in addon options with the format "ip:port" such as "192.168.178.1:9200"'
+        HOST=$(bashio::network.ipv4_address)
+        HOST="${HOST%/*}:9200"
+    fi
 
     # Final setup
     echo "... settings apps"
     #occ fulltextsearch:configure '{"search_platform":"ElasticSearchPlatform"}'
     $LAUNCHER fulltextsearch_elasticsearch:configure "{\"elastic_host\":\"http://$HOST:9200\"}" &>/dev/null
-    $LAUNCHER fulltextsearch_elasticsearch:configure "{\"elastic_index\":\"my_index\"}" &>/dev/null 
+    $LAUNCHER fulltextsearch_elasticsearch:configure "{\"elastic_index\":\"my_index\"}" &>/dev/null
     $LAUNCHER fulltextsearch_elasticsearch:configure "{\"analyzer_tokenizer\":\"standard\"}" &>/dev/null
     $LAUNCHER fulltextsearch:configure '{"search_platform":"OCA\\FullTextSearch_Elasticsearch\\Platform\\ElasticSearchPlatform"}' &>/dev/null || true
-    $LAUNCHER files_fulltextsearch:configure "{\"files_pdf\":\"1\",\"files_office\":\"1\"}" &>/dev/null || true 
+    $LAUNCHER files_fulltextsearch:configure "{\"files_pdf\":\"1\",\"files_office\":\"1\"}" &>/dev/null || true
 
     # Is server detected
-   # if [ curl $HOST ] &>/dev/null; then
-        # Wait further for cache for index to work
-        echo "Waiting for a few seconds before indexing starts..." 
-        sleep 10s
-        if $LAUNCHER fulltextsearch:index &>/dev/null; then
-            bashio::log.info "Full Text Search was successfully installed using elasticsearch server $HOST!"
-        
+    # if [ curl $HOST ] &>/dev/null; then
+    # Wait further for cache for index to work
+    echo "Waiting for a few seconds before indexing starts..."
+    sleep 10s
+    if $LAUNCHER fulltextsearch:index &>/dev/null; then
+        bashio::log.info "Full Text Search was successfully installed using elasticsearch server $HOST!"
 
-   else
-       bashio::log.warning "Elasticsearch can't connect. Please manually define its server in the options"
-   fi
+    else
+
+        bashio::log.warning "Elasticsearch can't connect. Please manually define its server in the options"
+    fi
 else
-echo "Full_Text_Search option not set"
+    echo "Full_Text_Search option not set"
 fi
diff --git a/nextcloud/root/etc/cont-init.d/99-ocr b/nextcloud/root/etc/cont-init.d/99-ocr
--- a/nextcloud/root/etc/cont-init.d/99-ocr
+++ b/nextcloud/root/etc/cont-init.d/99-ocr
@@ -1,12 +1,12 @@
 #!/usr/bin/with-contenv bashio
 
 LAUNCHER="sudo -u abc php /data/config/www/nextcloud/occ" || bashio::log.info "/data/config/www/nextcloud/occ not found"
-    if ! bashio::fs.file_exists '/data/config/www/nextcloud/occ'; then
-        LAUNCHER=$(find / -name "occ" -print -quit)
-    fi || bashio::log.info "occ not found"
+if ! bashio::fs.file_exists '/data/config/www/nextcloud/occ'; then
+    LAUNCHER=$(find / -name "occ" -print -quit)
+fi || bashio::log.info "occ not found"
 
 # Make sure there is an Nextcloud installation
-if ! [ "$($LAUNCHER -V)" ]; then
+if [[ $($LAUNCHER -V) == *"not installed"* ]]; then
     bashio::log.warning "It seems there is no Nextcloud server installed. Please restart the addon after initialization of the user."
     exit 0
 fi
